// Skills Data - Mock data for the skills browser
const skillsData = [
    {
        id: "web-search",
        name: "web-search",
        displayName: "Web Search",
        description: "搜索网络信息，获取最新资讯和参考资料。支持多种搜索引擎。",
        author: "OpenClaw Team",
        category: "搜索",
        icon: "🔍",
        tags: ["search", "web", "information"],
        installs: 45200,
        rating: 4.8,
        version: "2.1.0",
        command: "npx clawhub@latest install web-search"
    },
    {
        id: "github",
        name: "github",
        displayName: "GitHub",
        description: "与 GitHub 仓库交互，查看 issues、PR、提交代码等。",
        author: "OpenClaw Team",
        category: "开发工具",
        icon: "🐙",
        tags: ["github", "git", "development"],
        installs: 38900,
        rating: 4.9,
        version: "3.0.1",
        command: "npx clawhub@latest install github"
    },
    {
        id: "weather",
        name: "weather",
        displayName: "Weather",
        description: "获取全球任意城市的实时天气和未来预报。",
        author: "Community",
        category: "生活",
        icon: "🌤️",
        tags: ["weather", "forecast", "lifestyle"],
        installs: 32100,
        rating: 4.6,
        version: "1.5.2",
        command: "npx clawhub@latest install weather"
    },
    {
        id: "todo",
        name: "todo",
        displayName: "Todo Manager",
        description: "任务管理工具，创建、跟踪和完成待办事项。",
        author: "OpenClaw Team",
        category: "生产力",
        icon: "✅",
        tags: ["todo", "productivity", "tasks"],
        installs: 29800,
        rating: 4.7,
        version: "2.0.0",
        command: "npx clawhub@latest install todo"
    },
    {
        id: "browser",
        name: "browser",
        displayName: "Browser",
        description: "自动化浏览器操作，网页抓取、表单填写、截图等。",
        author: "OpenClaw Team",
        category: "自动化",
        icon: "🌐",
        tags: ["browser", "automation", "scraping"],
        installs: 27500,
        rating: 4.8,
        version: "2.2.1",
        command: "npx clawhub@latest install browser"
    },
    {
        id: "filesystem",
        name: "filesystem",
        displayName: "File System",
        description: "文件系统操作，读取、写入、搜索和管理本地文件。",
        author: "OpenClaw Team",
        category: "系统工具",
        icon: "📁",
        tags: ["files", "filesystem", "system"],
        installs: 41200,
        rating: 4.9,
        version: "3.1.0",
        command: "npx clawhub@latest install filesystem"
    },
    {
        id: "calculator",
        name: "calculator",
        displayName: "Calculator",
        description: "高级计算器，支持数学运算、单位转换和科学计算。",
        author: "Community",
        category: "工具",
        icon: "🧮",
        tags: ["math", "calculator", "tools"],
        installs: 18400,
        rating: 4.5,
        version: "1.3.0",
        command: "npx clawhub@latest install calculator"
    },
    {
        id: "code-runner",
        name: "code-runner",
        displayName: "Code Runner",
        description: "在沙箱环境中执行代码片段，支持多种编程语言。",
        author: "OpenClaw Team",
        category: "开发工具",
        icon: "💻",
        tags: ["code", "execution", "development"],
        installs: 35600,
        rating: 4.7,
        version: "2.0.3",
        command: "npx clawhub@latest install code-runner"
    },
    {
        id: "slack",
        name: "slack",
        displayName: "Slack",
        description: "Slack 集成，发送消息、管理频道、获取通知。",
        author: "Community",
        category: "通讯",
        icon: "💬",
        tags: ["slack", "messaging", "communication"],
        installs: 22300,
        rating: 4.6,
        version: "1.8.0",
        command: "npx clawhub@latest install slack"
    },
    {
        id: "notion",
        name: "notion",
        displayName: "Notion",
        description: "Notion 集成，管理页面、数据库和工作空间。",
        author: "Community",
        category: "生产力",
        icon: "📝",
        tags: ["notion", "notes", "productivity"],
        installs: 26700,
        rating: 4.7,
        version: "2.1.2",
        command: "npx clawhub@latest install notion"
    },
    {
        id: "image-gen",
        name: "image-gen",
        displayName: "Image Generator",
        description: "使用 AI 生成图像，支持多种风格和尺寸。",
        author: "OpenClaw Team",
        category: "AI",
        icon: "🎨",
        tags: ["ai", "image", "generation"],
        installs: 44500,
        rating: 4.8,
        version: "2.3.0",
        command: "npx clawhub@latest install image-gen"
    },
    {
        id: "database",
        name: "database",
        displayName: "Database",
        description: "数据库操作，支持 SQL 和 NoSQL 数据库查询。",
        author: "OpenClaw Team",
        category: "开发工具",
        icon: "🗄️",
        tags: ["database", "sql", "data"],
        installs: 19800,
        rating: 4.6,
        version: "1.9.1",
        command: "npx clawhub@latest install database"
    },
    {
        id: "translator",
        name: "translator",
        displayName: "Translator",
        description: "多语言翻译工具，支持 100+ 种语言互译。",
        author: "Community",
        category: "工具",
        icon: "🌐",
        tags: ["translation", "language", "tools"],
        installs: 31200,
        rating: 4.7,
        version: "2.0.1",
        command: "npx clawhub@latest install translator"
    },
    {
        id: "calendar",
        name: "calendar",
        displayName: "Calendar",
        description: "日历管理，查看日程、创建事件、设置提醒。",
        author: "OpenClaw Team",
        category: "生产力",
        icon: "📅",
        tags: ["calendar", "schedule", "productivity"],
        installs: 24500,
        rating: 4.5,
        version: "1.7.0",
        command: "npx clawhub@latest install calendar"
    },
    {
        id: "email",
        name: "email",
        displayName: "Email",
        description: "邮件管理，发送、接收和组织电子邮件。",
        author: "OpenClaw Team",
        category: "通讯",
        icon: "📧",
        tags: ["email", "communication", "productivity"],
        installs: 28900,
        rating: 4.6,
        version: "2.0.2",
        command: "npx clawhub@latest install email"
    },
    {
        id: "home-assistant",
        name: "home-assistant",
        displayName: "Home Assistant",
        description: "智能家居控制，管理灯光、温度、安防等设备。",
        author: "Community",
        category: "智能家居",
        icon: "🏠",
        tags: ["smart-home", "iot", "automation"],
        installs: 15600,
        rating: 4.8,
        version: "1.5.0",
        command: "npx clawhub@latest install home-assistant"
    },
    {
        id: "stock",
        name: "stock",
        displayName: "Stock Tracker",
        description: "股票追踪，实时行情、图表分析和投资组合管理。",
        author: "Community",
        category: "金融",
        icon: "📈",
        tags: ["stocks", "finance", "trading"],
        installs: 21300,
        rating: 4.5,
        version: "1.6.1",
        command: "npx clawhub@latest install stock"
    },
    {
        id: "news",
        name: "news",
        displayName: "News Aggregator",
        description: "新闻聚合，获取最新头条和个性化资讯推荐。",
        author: "Community",
        category: "信息",
        icon: "📰",
        tags: ["news", "information", "rss"],
        installs: 19800,
        rating: 4.4,
        version: "1.4.0",
        command: "npx clawhub@latest install news"
    },
    {
        id: "docker",
        name: "docker",
        displayName: "Docker",
        description: "Docker 管理，容器操作、镜像构建和日志查看。",
        author: "OpenClaw Team",
        category: "DevOps",
        icon: "🐳",
        tags: ["docker", "containers", "devops"],
        installs: 32400,
        rating: 4.7,
        version: "2.1.0",
        command: "npx clawhub@latest install docker"
    },
    {
        id: "kubernetes",
        name: "kubernetes",
        displayName: "Kubernetes",
        description: "K8s 集群管理，Pod、Service、Deployment 操作。",
        author: "OpenClaw Team",
        category: "DevOps",
        icon: "☸️",
        tags: ["kubernetes", "k8s", "devops"],
        installs: 18700,
        rating: 4.6,
        version: "1.8.0",
        command: "npx clawhub@latest install kubernetes"
    },
    {
        id: "aws",
        name: "aws",
        displayName: "AWS",
        description: "AWS 云服务管理，EC2、S3、Lambda 等资源操作。",
        author: "Community",
        category: "云服务",
        icon: "☁️",
        tags: ["aws", "cloud", "infrastructure"],
        installs: 25600,
        rating: 4.5,
        version: "2.0.0",
        command: "npx clawhub@latest install aws"
    },
    {
        id: "spotify",
        name: "spotify",
        displayName: "Spotify",
        description: "Spotify 音乐控制，播放、搜索、管理播放列表。",
        author: "Community",
        category: "娱乐",
        icon: "🎵",
        tags: ["spotify", "music", "entertainment"],
        installs: 28900,
        rating: 4.7,
        version: "1.9.0",
        command: "npx clawhub@latest install spotify"
    },
    {
        id: "youtube",
        name: "youtube",
        displayName: "YouTube",
        description: "YouTube 视频搜索、播放列表管理和下载。",
        author: "Community",
        category: "娱乐",
        icon: "📺",
        tags: ["youtube", "video", "entertainment"],
        installs: 34200,
        rating: 4.6,
        version: "2.2.0",
        command: "npx clawhub@latest install youtube"
    },
    {
        id: "pdf",
        name: "pdf",
        displayName: "PDF Tools",
        description: "PDF 处理工具，合并、拆分、转换和提取文本。",
        author: "Community",
        category: "文档",
        icon: "📄",
        tags: ["pdf", "documents", "tools"],
        installs: 22400,
        rating: 4.5,
        version: "1.6.0",
        command: "npx clawhub@latest install pdf"
    }
];

// Categories
const skillCategories = [
    { id: "all", name: "全部", icon: "🌟" },
    { id: "搜索", name: "搜索", icon: "🔍" },
    { id: "开发工具", name: "开发工具", icon: "💻" },
    { id: "生产力", name: "生产力", icon: "⚡" },
    { id: "自动化", name: "自动化", icon: "🤖" },
    { id: "系统工具", name: "系统工具", icon: "⚙️" },
    { id: "工具", name: "工具", icon: "🧰" },
    { id: "通讯", name: "通讯", icon: "💬" },
    { id: "AI", name: "AI", icon: "🧠" },
    { id: "智能家居", name: "智能家居", icon: "🏠" },
    { id: "金融", name: "金融", icon: "💰" },
    { id: "信息", name: "信息", icon: "ℹ️" },
    { id: "DevOps", name: "DevOps", icon: "🚀" },
    { id: "云服务", name: "云服务", icon: "☁️" },
    { id: "娱乐", name: "娱乐", icon: "🎮" },
    { id: "文档", name: "文档", icon: "📄" },
    { id: "生活", name: "生活", icon: "🌱" }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { skillsData, skillCategories };
}
